### ISSUE TITLE
Is it possible to monitor multiple mysql clusters?

### ISSUE THREAD

**Issue by hadesfeng** [yandex/mysync#48]
I may need to monitor multiple mysql clusters

**Comment by teem0n** [comment]
You have to configure mysync services for each cluster separately then.

**Comment by hadesfeng** [comment]
I may understand a little bit now. Is it possible to share zookeeper clusters, 
but mysync needs to be deployed independently with each mysql cluster?

**Comment by teem0n** [comment]
You may share zookeeker cluster by using different namespaces (in "zookeeper" config section).
And yes, you deploy mysync independently on each host within each cluster and using same zookeeper but different namespaces in mysync.yaml

**Comment by hadesfeng** [comment]
OK, thank you very much for your reply！
